// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace NguyenThaoNguyen451.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230104014848_NTN451")]
    partial class NTN451
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("NguyenThaoNguyen451.Models.NTN451", b =>
                {
                    b.Property<string>("NTNId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NTNName")
                        .HasColumnType("TEXT");

                    b.HasKey("NTNId");

                    b.ToTable("NTN451");
                });

            modelBuilder.Entity("NguyenThaoNguyen451.Models.UniversityNTN451", b =>
                {
                    b.Property<string>("UniversityId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UniversityName")
                        .HasColumnType("TEXT");

                    b.HasKey("UniversityId");

                    b.ToTable("UniversityNTN451");
                });
#pragma warning restore 612, 618
        }
    }
}
